# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            MoNA
tagline:          'Multi-omics Network Analytics Group'
description:      'Multi-omics Network Analytics Group'
url:              'http://multiomics-analytics-group.github.io'
baseurl:          ''     

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

# paginate:         5

# Custom vars
github:
  repo:           https://github.com/Multiomics-Analytics-Group
