# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            MoNA
tagline:          'MoNA'
description:      'Testing'
url:              'http://multiomics-analytics-group.github.io'
baseurl:          ''     

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          5

github:
  repo:           https://github.com/Multiomics-Analytics-Group
